import type { Metadata } from 'next';
import localfont from 'next/font/local';
import { Providers } from '../providers';
import InoguezLogo from '@/components/inoguez-logo';
import '../globals.css';
import MobileNavbar from '@/components/mobile-navbar';
import { cn } from '@nextui-org/react';
import { LuDribbble, LuGithub, LuLinkedin } from 'react-icons/lu';
import { SiAstro } from 'react-icons/si';
import { i18n, type Locale } from '@/i18n-config';
import fetchApi from '@/libs/strapi';
const myFont = localfont({ src: '../../fonts/Nohemi-VF.ttf' });
import { ApiNavigationNavigation } from '@inoguez/strapi-types/ContentTypes';
import Link from 'next/link';
import { ReactLenis, useLenis } from '@/libs/lenis';
import Header from '@/components/header';
export const metadata: Metadata = {
  title: 'iNoguez',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

async function getNavigation(lang: string) {
  const nav = await fetchApi<ApiNavigationNavigation[]>({
    endpoint: 'navigations',
    query: { locale: lang },
    wrappedByKey: 'data',
  });
  return nav;
}
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const navigationInfo = await getNavigation(params.lang);
  return (
    <html lang='en' className='dark'>
      <body className={cn('!bg-foreground', myFont.className)}>
        <ReactLenis root>
          <div
            vaul-drawer-wrapper=''
            className='relative wrapper min-h-dvh rounded-b-[3rem]'
          >
            <Header navigationInfo={navigationInfo} />

            <div className='p-6 pt-28 md:pt-32'>
              <Providers data-scroll data-scroll-speed>
                {children}
              </Providers>
            </div>
          </div>
          <footer className='flex flex-col gap-4 bg-foreground rounded-3xl p-6 transition-colors duration-700'>
            <div className='flex items-center gap-4 text-background'>
              <div className='px-4'>
                <InoguezLogo className='fill-background transition-colors  duration-700' />
              </div>
              <nav className='flex-1 grid grid-cols-2 gap-2 font-light transition-colors duration-700'>
                {navigationInfo?.map((item, index) => (
                  <Link href={'#'} key={index}>
                    <span>{String(item?.attributes?.title)}</span>
                  </Link>
                ))}
              </nav>
            </div>
            <div className='flex tems-center text-background text-2xl transition-colors duration-700'>
              <div className='flex-1 flex justify-evenly'>
                <LuGithub />
                <LuLinkedin />
                <LuDribbble />
              </div>
            </div>
          </footer>
        </ReactLenis>
      </body>
    </html>
  );
}
